name: flame_oxygen
description: Integrate the Oxygen ECS with the Flame Engine.
version: 0.1.7
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flame: ^1.5.0
  flutter:
    sdk: flutter
  oxygen:
    git:
      url: https://github.com/clover-leaf/oxygen.git
      ref: main

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.1.3